### ISSUE TITLE
`NoSuchMethodError` using `proto-google-common-protos-scalapb_0.11` with version `0.11.3` of `compilerplugin`

### ISSUE THREAD

**Issue by therockstorm** [scalapb/common-protos#105] opened 2021-05-24 20:42 UTC
When using `"com.thesamet.scalapb.common-protos" %% "proto-google-common-protos-scalapb_0.11" % "1.18.1-1"` with `"com.thesamet.scalapb" %% "compilerplugin" % "0.11.3"`, I get the following.

```java.lang.NoSuchMethodError: 'scalapb.GeneratedMessage scalapb.GeneratedMessageCompanion.parseFrom$(scalapb.GeneratedMessageCompanion, com.google.protobuf.CodedInputStream)'```

Using `dependencyBrowseTree`, it looks like common-protos is using version `0.11.0-M4`. Would a dependency update fix this?

**Comment by thesamet** [comment] 2021-06-10 14:49
Thanks for reporting. Closing since it is a duplicate of https://github.com/scalapb/ScalaPB/issues/1122

**Closed by thesamet** 2021-06-10 14:49 UTC

**Comment by thesamet** [comment] 2021-06-10 14:50
The current upstream blocker is https://github.com/googleapis/java-common-protos/issues/179

**Comment by therockstorm** [comment] 2021-06-10 14:57
Thanks for the update!
